# inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'test/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'
    - 'clock.rb'
    - 'app/jobs/application_job.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/channels/application_cable/channel.rb'
    - 'app/channels/application_cable/connection.rb'
    - 'app/views/examples/**/*'
    - 'app/models/example*'
  NewCops: enable
Style/Documentation:
  Enabled: false

